apiVersion: v1
kind: Service
metadata:
  name: backendapp
spec:
  ports:
    - port: 5432
  selector:
    app: hello
    tier: postgres
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backendapp
spec:
  selector:
    matchLabels:
      app: hello
      tier: postgres
      track: stable
  replicas: 1
  template:
    metadata:
      labels:
        app: hello
        tier: postgres
        track: stable
    spec:
      containers:
        - image: mypostgres-db:1.0.0
          name: mypostgres
          env:
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_DB
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "123456"
          ports:
            - containerPort: 5432
              name: mypostgres
