apiVersion: v1
kind: Service
metadata:
  name: frontendapp
spec:
  selector:
    app: hello
    tier: backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontendapp
spec:
  selector:
    matchLabels:
      app: hello
      tier: backend
      track: stable
  replicas: 7
  template:
    metadata:
      labels:
        app: hello
        tier: backend
        track: stable
    spec:
      containers:
        - name: accesoapp
          image: acceso-app:1.0.1
          ports:
            - name: http
              containerPort: 8000